require 'rubygems'
require 'rake'

# codecite testtask
require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/*_test.rb'
  test.verbose = true
end

task :default => :test
# codecite testtask

# codecite spectask
require 'spec/rake/spectask'

spec_files = FileList['spec/**/*_spec.rb']

desc "Run all specs"
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = spec_files
end

namespace :spec do
  desc "Run all specs with the doc formatter"
  Spec::Rake::SpecTask.new('doc') do |spec|
    spec.libs << 'lib' << 'spec'
    spec.spec_files = spec_files
    spec.spec_opts = %w[--format specdoc]
  end

  desc "Run all specs and generate HTML report"
  Spec::Rake::SpecTask.new('report') do |spec|
    spec.libs << 'lib' << 'spec'
    spec.spec_files = spec_files
    spec.spec_opts = %w[--format html:doc/specs.html --diff]
    spec.fail_on_error = false
  end

end
# codecite spectask


begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |test|
    test.libs << 'test'
    test.pattern = 'test/**/test_*.rb'
    test.verbose = true
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install rcov"
  end
end
